# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_role.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eget_role.proto\x12\x07getRole\"\x1d\n\x05Token\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"\x1f\n\x0fMessageResponse\x12\x0c\n\x04role\x18\x01 \x01(\t2J\n\x07GetRole\x12?\n\x11GetServerResponse\x12\x0e.getRole.Token\x1a\x18.getRole.MessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_role_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOKEN']._serialized_start=27
  _globals['_TOKEN']._serialized_end=56
  _globals['_MESSAGERESPONSE']._serialized_start=58
  _globals['_MESSAGERESPONSE']._serialized_end=89
  _globals['_GETROLE']._serialized_start=91
  _globals['_GETROLE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
