# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_token.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12update_token.proto\x12\x0bupdateToken\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\">\n\x0fMessageResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t2W\n\nValidToken\x12I\n\x11GetServerResponse\x12\x14.updateToken.Message\x1a\x1c.updateToken.MessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'update_token_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=35
  _globals['_MESSAGE']._serialized_end=61
  _globals['_MESSAGERESPONSE']._serialized_start=63
  _globals['_MESSAGERESPONSE']._serialized_end=125
  _globals['_VALIDTOKEN']._serialized_start=127
  _globals['_VALIDTOKEN']._serialized_end=214
# @@protoc_insertion_point(module_scope)
